export const genres = {
  "genres": [
    { "id": 1, "label": "Acțiune și Aventură", "slug": "action-adventure" },
    { "id": 2, "label": "Artă și Fotografie", "slug": "art-photography" },
    { "id": 3, "label": "Biografii și Memorii", "slug": "bio-memories" },
    { "id": 4, "label": "Business și Economie", "slug": "business-economy" },
    { "id": 5, "label": "Cărți pentru Copii", "slug": "kids" },
    { "id": 6, "label": "Clasici", "slug": "classics" },
    { "id": 7, "label": "Benzi Desenate și Manga", "slug": "comics-manga" },
    { "id": 8, "label": "Gastronomie și Rețete", "slug": "gastronomy" },
    { "id": 9, "label": "Educație și Dicționare", "slug": "education" },
    { "id": 10, "label": "Fantezie", "slug": "fantasy" },
    { "id": 11, "label": "Ficțiune Istorică", "slug": "historical-fiction" },
    { "id": 12, "label": "Istorie", "slug": "history" },
    { "id": 13, "label": "Horror", "slug": "horror" },
    { "id": 14, "label": "Umor", "slug": "humor" },
    { "id": 15, "label": "Mister și Crimă", "slug": "mistery-crime" },
    { "id": 16, "label": "Filozofie", "slug": "philosophy" },
    { "id": 17, "label": "Poezie", "slug": "poetry" },
    { "id": 18, "label": "Psihologie și Dezvoltare Personală", "slug": "psichology-personal-development" },
    { "id": 19, "label": "Religie și Spiritulitate", "slug": "religion-spirituality" },
    { "id": 20, "label": "Romance", "slug": "romance" },
    { "id": 21, "label": "Science Fiction", "slug": "science-fiction" },
    { "id": 22, "label": "Știință și Tehnologie", "slug": "science-technology" },
    { "id": 23, "label": "Self-Help", "slug": "self-help" },
    { "id": 24, "label": "Sănătate și Fitness", "slug": "health-fitness" },
    { "id": 25, "label": "Sociologie și Politică", "slug": "sociology-politics" },
    { "id": 26, "label": "Thriller și Suspans", "slug": "thriller-suspanse" },
    { "id": 27, "label": "Călătorii și Ghiduri", "slug": "travelling" },
    { "id": 28, "label": "Young Adult", "slug": "young-adult" },
    { "id": 29, "label": "Dark Romance", "slug": "dark-romance" },
    { "id": 30, "label": "Drama", "slug": "drama" }
  ]
}